{'name': 'Home Expense Tracker',
 'description': 'Daily home expenditure recording.',
 'license': "AGPL-3",
 'author': 'Biju Pattea',
 'depends': ['base', 'board', 'mail'],
 'data': [
     'security/expense_security.xml',
     'security/ir.model.access.csv',
     'views/expense_menu.xml',
     #     'views/view_dboard_expence.xml',
     'views/expense_view.xml',
     'views/sip_view.xml',
     'views/income_view.xml',
     'views/fd_view.xml',
     'views/cash_view.xml',
     'views/fd_kanban_view.xml',
     'views/totals_view.xml',
     #     'reports/expense_report.xml',
 ],
 'application': True,
 'installable': True,
 }
