{'name': 'Hospital Management',
 'description': 'Hospital Management Appilication.',
 'license': "AGPL-3",
 'author': 'Biju Pattera',
 'category': 'Hospital',
 'depends': ['base', 'board', 'mail', 'product'],
 'data': [
     'security/hospital_security.xml',
     'security/ir.model.access.csv',
     'data/patient_tag_data.xml',
     'data/patient.tag.csv',
     'data/sequence.xml',
     'wizard/cancel_appointment.xml',
     'views/hospital_menu.xml',
     'views/patient.xml',
     'views/users.xml',
     'views/patient_tag.xml',
     'views/appointment.xml',
     'views/board.xml',
 ],
 'application': True,
 'installable': True,
 'assets': {},
 }
